"use client";

import { motion, AnimatePresence, useInView } from "framer-motion";
import { useState, useRef, useEffect } from "react";
import Image from "next/image";
import PastProjectCard from "./PastProjectCard";

export interface Project {
  title: string;
  description: string;
  imgSrc?: string;
  url?: string;
}

// Separate arrays per category (placeholders)
const CxC2025Projects: Project[] = [
  {
    title: "Lasagna",
    description:
      "AI-powered next-action recommendations to boost user engagement, streamline decision-making, and enhance personalized experiences with intelligent automation.",
    imgSrc: "/past_projects/federato_data_challenge.png",
    url: "https://devpost.com/software/federato-data-challenge",
  },
  {
    title: "Macrodata Refinement",
    description: "Submission to CxC 2025 SAP Challenge, Poverty Analytics",
    imgSrc: "/past_projects/macrodata_refinement.png",
    url: "https://devpost.com/software/cxc-2025-sap-challenge",
  },
  {
    title: "Adaptive Workflow Engine",
    description:
      "Leveraging causal inference, predictive modeling and interactive graph visualizations to optimize user navigation and enhance engagement on the Federato RiskOps platform",
    imgSrc: "/past_projects/workflow_engine.png",
    url: "https://devpost.com/software/cxc-2025-sap-challenge",
  },
];

const CxC2024Projects: Project[] = [
  {
    title: "Monke",
    description:
      "Predict missing IAQ values with the power of Tensorflow, multivariate LSTMs and monkes!",
    imgSrc: "/past_projects/monkes.jpeg",
    url: "https://devpost.com/software/monke-y2s5fc",
  },
  {
    title: "Quadreal Challenge",
    description:
      "We attempt to devise a solution to predict missing values for data generated by Indoo Air Quality sensors in the occasion of outages.",
    imgSrc: "/past_projects/quadreal.jpg",
    url: "https://devpost.com/software/quadreal-challenge",
  },
  {
    title: "Our ML Churney",
    description:
      "Leveraging historical data from Infinite Investment Systems, research on wealth management, and ML techniques to build a highly performant predictive model.",
    imgSrc: "/past_projects/our_ml_journey.jpg",
    url: "https://devpost.com/software/our-ml-churney",
  },
];

const CxC2023Projects: Project[] = [
  {
    title: "GNN + LSTM embedding",
    description: "Classification model for binding sites using an LSTM + GNN",
    imgSrc: "/past_projects/gnn_lstm.jpg",
    url: "https://devpost.com/software/lstm-embeddings-gnn",
  },
  {
    title: "j4noronh_Intact",
    description:
      "Trained a Medical Document classifier using HuggingFace's XLNet NLP Model. The project contains the predictions, and a notebook outlining the process.",
    imgSrc: "/past_projects/j4noronh.jpg",
    url: "https://devpost.com/software/j4noronh_intact_cxc2023",
  },
  {
    title: "Team Snowflakes",
    description:
      "A classification model to predict the drug binding sites on AlphaFold2-predicted proteins.",
    imgSrc: "/past_projects/snowflakes.png",
    url: "https://devpost.com/software/cyclia-submission",
  },
];

export function PastProjects() {
  return (
    <div className="relative w-full h-full py-20 overflow-hidden">
      <h2 className="text-3xl md:text-4xl font-semibold mb-24 text-center">
        Past Projects
      </h2>
      {/* UFO Categories */}
      <div className="mx-auto min-h-[900px] flex flex-col gap-16 md:relative md:block">
        {/* Mobile */}
        <div className="block lg:hidden">
          <div key="cxc-2025" className="mb-16 flex flex-col items-center">
            <UFO category="CxC 2025" />
            <div className="flex flex-col gap-6">
              {CxC2025Projects.map((project) => (
                <PastProjectCard key={project.title} {...project} />
              ))}
            </div>
          </div>
          <div key="cxc-2024" className="mb-16 flex flex-col items-center">
            <UFO category="CxC 2024" />
            <div className="flex flex-col gap-6">
              {CxC2024Projects.map((project) => (
                <PastProjectCard key={project.title} {...project} />
              ))}
            </div>
          </div>
          <div key="cxc-2023" className="mb-16 flex flex-col items-center">
            <UFO category="CxC 2023" />
            <div className="flex flex-col gap-6">
              {CxC2023Projects.map((project) => (
                <PastProjectCard key={project.title} {...project} />
              ))}
            </div>
          </div>
        </div>
        {/* Desktop */}
        <div className="hidden lg:block">
          <div className="flex flex-row justify-between items-start w-full max-w-7xl mx-auto gap-8">
            <div className="flex flex-col items-center flex-1">
              <UFO category="CxC 2025" />
              <div className="flex flex-wrap gap-3 max-w-xl items-center justify-center mt-6">
                {CxC2025Projects.map((project) => (
                  <PastProjectCard key={project.title} {...project} />
                ))}
              </div>
            </div>
            <div className="flex flex-col items-center flex-1">
              <UFO category="CxC 2024" />
              <div className="flex flex-wrap gap-3 max-w-xl items-center justify-center mt-6">
                {CxC2024Projects.map((project) => (
                  <PastProjectCard key={project.title} {...project} />
                ))}
              </div>
            </div>
          </div>
          <div className="absolute top-[65%] left-[50%] flex flex-col items-center -translate-x-1/2">
            <UFO category="CxC 2023" />
            <div className="flex flex-row gap-3 items-center justify-center mt-6">
              {CxC2023Projects.map((project) => (
                <PastProjectCard key={project.title} {...project} />
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function UFO({ category }: { category: string }) {
  const ref = useRef<HTMLDivElement | null>(null);
  const inView = useInView(ref, { amount: 0.25 });
  const [hasBeenInView, setHasBeenInView] = useState(false);
  useEffect(() => {
    if (inView) setHasBeenInView(true);
  }, [inView]);

  const isActiveFinal = hasBeenInView;
  const gradId = `beamFade-${category.replace(/\s+/g, "-")}`;

  return (
    <div className="relative inline-block" ref={ref}>
      <div className="absolute left-1/2 -translate-x-1/2 -top-12 flex flex-col items-center select-none w-full">
        <p
          className="text-white font-semibold tracking-wider text-base py-2 whitespace-nowrap"
          style={{
            filter: "drop-shadow(0 0 4px rgba(255,255,255,0.5))",
          }}
        >
          {category}
        </p>
      </div>
      <motion.div
        className="relative"
        animate={{
          y: [0, -10, 0],
        }}
        transition={{
          y: {
            duration: 3,
            repeat: Infinity,
            ease: "easeInOut",
          },
          layout: {
            duration: 0,
          },
        }}
      >
        {/* UFO Image with White Glow */}
        <div className="relative">
          <div
            className="absolute inset-0 bg-white rounded-full blur-2xl opacity-25 animate-pulse"
            style={{ animationDuration: "4s" }}
          ></div>

          <Image
            src="/past_projects/ufo.png"
            alt={`${category} UFO`}
            width={316}
            height={119}
            className="relative w-36 h-14 object-contain"
            style={{
              filter:
                "drop-shadow(0 0 6px rgba(255,255,255,0.6)) drop-shadow(0 0 12px rgba(255,255,255,0.4))",
            }}
          />
          {/* Blinking lights */}
          <div
            className="absolute top-2 right-1 w-[1.5px] h-[1.5px] bg-white rounded-full opacity-80 animate-ping"
            style={{ animationDuration: "2s", animationDelay: "0s" }}
          ></div>
          <div
            className="absolute bottom-3 left-0 w-1 h-1 bg-white rounded-full opacity-70 animate-ping"
            style={{ animationDuration: "2s", animationDelay: "1s" }}
          ></div>
          <div
            className="absolute top-1/2 right-0 w-[2.5px] h-[2.5px] bg-white rounded-full opacity-60 animate-ping"
            style={{ animationDuration: "2s", animationDelay: "1.5s" }}
          ></div>
          <div
            className="absolute top-0 left-1/3 w-[1.5px] h-[1.5px] bg-white rounded-full opacity-60 animate-ping"
            style={{ animationDuration: "2s", animationDelay: "2.5s" }}
          ></div>
          <div
            className="absolute top-4 left-2 w-[2px] h-[2px] bg-white rounded-full opacity-75 animate-ping"
            style={{ animationDuration: "2.5s", animationDelay: "0.5s" }}
          ></div>
          <div
            className="absolute bottom-2 right-3 w-[1px] h-[1px] bg-white rounded-full opacity-65 animate-ping"
            style={{ animationDuration: "3s", animationDelay: "1.2s" }}
          ></div>
          <div
            className="absolute top-1/3 left-1/4 w-[3px] h-[3px] bg-white rounded-full opacity-70 animate-ping"
            style={{ animationDuration: "2.2s", animationDelay: "0.8s" }}
          ></div>
          <div
            className="absolute bottom-1/3 right-1/4 w-[1.5px] h-[1.5px] bg-white rounded-full opacity-85 animate-ping"
            style={{ animationDuration: "2.8s", animationDelay: "1.8s" }}
          ></div>
          <div
            className="absolute top-1/4 right-1/3 w-[2px] h-[2px] bg-white rounded-full opacity-60 animate-ping"
            style={{ animationDuration: "3.5s", animationDelay: "2.2s" }}
          ></div>
          <div
            className="absolute bottom-1/4 left-1/2 w-[1px] h-[1px] bg-white rounded-full opacity-70 animate-ping"
            style={{ animationDuration: "2.3s", animationDelay: "0.3s" }}
          ></div>
          <div
            className="absolute top-3 right-1/2 w-[2.5px] h-[2.5px] bg-white rounded-full opacity-75 animate-ping"
            style={{ animationDuration: "2.7s", animationDelay: "1.6s" }}
          ></div>
          <div
            className="absolute bottom-4 left-1/3 w-[1.5px] h-[1.5px] bg-white rounded-full opacity-65 animate-ping"
            style={{ animationDuration: "3.2s", animationDelay: "2.1s" }}
          ></div>
        </div>

        {/* Beam/Ray effect — single smooth SVG beam with mask and seamless motion */}
        <AnimatePresence>
          {isActiveFinal && (
            <motion.div
              initial={{ opacity: 0, scaleY: 0 }}
              animate={{ opacity: 1, scaleY: 1 }}
              exit={{ opacity: 0, scaleY: 0 }}
              transition={{ duration: 0.9, ease: "easeInOut" }}
              className="absolute left-1/2 -translate-x-1/2 top-full pointer-events-none"
              style={{
                width: "300px",
                height: "320px",
                clipPath: "path('M 100 0 Q 150 11, 200 0 L 300 256 L 0 256 Z')",
                transformOrigin: "50% 0%",
                maskImage:
                  "linear-gradient(to bottom, rgba(0,0,0,1) 0%, rgba(0,0,0,0.6) 50%, rgba(0,0,0,0.2) 75%, rgba(0,0,0,0) 100%)",
                WebkitMaskImage:
                  "linear-gradient(to bottom, rgba(0,0,0,1) 0%, rgba(0,0,0,0.6) 50%, rgba(0,0,0,0.2) 75%, rgba(0,0,0,0) 100%)",
              }}
            >
              {/* beam */}
              <svg
                className="absolute inset-0 w-full h-full pointer-events-none"
                viewBox="0 0 300 320"
                preserveAspectRatio="none"
                aria-hidden
              >
                <defs>
                  <linearGradient
                    id={`${gradId}-smooth`}
                    x1="0"
                    x2="0"
                    y1="0"
                    y2="1"
                  >
                    <stop offset="0%" stopColor="rgba(220,220,230,0.48)" />
                    <stop offset="50%" stopColor="rgba(220,220,230,0.10)" />
                    <stop offset="100%" stopColor="rgba(220,220,230,0)" />
                  </linearGradient>
                  <filter
                    id={`${gradId}-blur2`}
                    x="-30%"
                    y="-30%"
                    width="160%"
                    height="160%"
                  >
                    <feGaussianBlur stdDeviation="10" />
                  </filter>
                </defs>
                <path
                  d="M 100 0 Q 150 11, 200 0 L 300 320 L 0 320 Z"
                  fill={`url(#${gradId}-smooth)`}
                  filter={`url(#${gradId}-blur2)`}
                />
              </svg>

              {/*  skeleton-loader style shimmer overlay */}
              <div className="absolute inset-0 overflow-hidden pointer-events-none">
                <motion.div
                  className="absolute top-0 left-[-60%] h-full"
                  style={{
                    width: "220%",
                    transform: "skewY(-6deg)",
                    background:
                      "linear-gradient(90deg, rgba(255,255,255,0) 0%, rgba(245,245,250,0.18) 45%, rgba(245,245,250,0.06) 55%, rgba(255,255,255,0) 100%)",
                    mixBlendMode: "screen",
                    filter: "blur(6px)",
                    opacity: 0.8,
                  }}
                  animate={{ x: ["-60%", "60%"] }}
                  transition={{
                    duration: 3,
                    repeat: Infinity,
                    ease: "linear",
                    repeatType: "loop",
                  }}
                />
              </div>

              {/* subtle smooth motion so loop is seamless */}
              <motion.div
                className="absolute inset-0"
                animate={{ scaleY: [1, 1.02, 1], y: [0, -5, 0] }}
                transition={{
                  duration: 2,
                  repeat: Infinity,
                  repeatType: "mirror",
                  ease: "easeInOut",
                }}
              />
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>
    </div>
  );
}
